//   Author:   Tadhg Coffey
//   Date  :   5/19/14
//   Homework assignment : Quiz 2
//   File: R.java from Send Birthday Greeting
//   Objective : Read (2) text files: One with a birthday greeting 
//             and the second containing the user's contacts with 
//             birthday dates. Contacts are placed in a table.When 
//             current date matches a date in the contacts table, 
//             the user will be alerted and can choose to send a 
//             birthday greeting to the contact.
//****************************************************************

/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.sendbirthdaygreeting.app;

public final class R 
{
    public static final class attr 
    {
    }
    public static final class dimen 
    {
        public static final int activity_horizontal_margin
        =0x7f050000;
        public static final int activity_vertical_margin
        =0x7f050001;
    }
    public static final class drawable 
    {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id 
    {
        public static final int action_settings=0x7f09000b;
        public static final int sendButtonId=0x7f090003;
        public static final int textView=0x7f090000;
        public static final int textView2=0x7f090001;
        public static final int textView3=0x7f090002;
        public static final int textView4=0x7f09000a;
        public static final int textView5=0x7f090006;
        public static final int tvBirthday_Id=0x7f090008;
        public static final int tvEmail_Id=0x7f090007;
        public static final int tvName_Id=0x7f090005;
        public static final int tvPhone_Id=0x7f090009;
        public static final int tvSMS_Id=0x7f090004;
    }
    public static final class layout 
    {
        public static final int activity_send_birthday_greeting
        =0x7f030000;
    }
    public static final class menu 
    {
        public static final int send_birthday_greeting=0x7f080000;
    }
    public static final class raw 
    {
        public static final int birthday_wish=0x7f040000;
        public static final int contacts=0x7f040001;
    }
    public static final class string 
    {
        public static final int action_settings=0x7f060000;
        public static final int app_name=0x7f060001;
        public static final int hello_world=0x7f060002;
    }
    public static final class style 
    {
        /**  Customize your theme here. 
         */
        public static final int AppTheme=0x7f070000;
    }
}
